feat: add language code to android
larryaasen/upgrader pull request #217
Opened 2022-09-14 12:40 UTC by humanolaranja

# The problem
### today if you have an international app with different release notes languages, the release notes in android will just display in english

# The solution
### add the `hl` paramether in the url to call the play store with the correct language

# Examples
### [English:](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=en)
<img width="858" alt="image" src="https://user-images.githubusercontent.com/18094686/190154543-d0ddb56b-5d9a-4ad3-b487-e050b3602cee.png">
<img width="914" alt="image" src="https://user-images.githubusercontent.com/18094686/190154601-bfe462cc-dfa6-4bd6-89d1-480f066f2328.png">
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/18094686/190155891-dadbaf6b-3586-4601-85ba-20b8b72d3c0d.png">

### [Spanish:](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox&hl=es)
<img width="848" alt="image" src="https://user-images.githubusercontent.com/18094686/190155080-8bd2499f-f440-4a7b-91bb-163bf833b0a8.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/18094686/190155133-7c23d23f-e628-4e22-a96a-a3583fb4abb4.png">
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/18094686/190156178-74d48abf-e3c1-4569-ac16-bf6efd69c6e6.png">

# Supported codes
```
[
  {
    "language_code": "af",
    "language_name": "Afrikaans"
  },
  {
    "language_code": "ak",
    "language_name": "Akan"
  },
  {
    "language_code": "sq",
    "language_name": "Albanian"
  },
  {
    "language_code": "ws",
    "language_name": "Samoa"
  },
  {
    "language_code": "am",
    "language_name": "Amharic"
  },
  {
    "language_code": "ar",
    "language_name": "Arabic"
  },
  {
    "language_code": "hy",
    "language_name": "Armenian"
  },
  {
    "language_code": "az",
    "language_name": "Azerbaijani"
  },
  {
    "language_code": "eu",
    "language_name": "Basque"
  },
  {
    "language_code": "be",
    "language_name": "Belarusian"
  },
  {
    "language_code": "bem",
    "language_name": "Bemba"
  },
  {
    "language_code": "bn",
    "language_name": "Bengali"
  },
  {
    "language_code": "bh",
    "language_name": "Bihari"
  },
  {
    "language_code": "xx-bork",
    "language_name": "Bork, bork, bork!"
  },
  {
    "language_code": "bs",
    "language_name": "Bosnian"
  },
  {
    "language_code": "br",
    "language_name": "Breton"
  },
  {
    "language_code": "bg",
    "language_name": "Bulgarian"
  },
  {
    "language_code": "bt",
    "language_name": "Bhutanese"
  },
  {
    "language_code": "km",
    "language_name": "Cambodian"
  },
  {
    "language_code": "ca",
    "language_name": "Catalan"
  },
  {
    "language_code": "chr",
    "language_name": "Cherokee"
  },
  {
    "language_code": "ny",
    "language_name": "Chichewa"
  },
  {
    "language_code": "zh-cn",
    "language_name": "Chinese (Simplified)"
  },
  {
    "language_code": "zh-tw",
    "language_name": "Chinese (Traditional)"
  },
  {
    "language_code": "co",
    "language_name": "Corsican"
  },
  {
    "language_code": "hr",
    "language_name": "Croatian"
  },
  {
    "language_code": "cs",
    "language_name": "Czech"
  },
  {
    "language_code": "da",
    "language_name": "Danish"
  },
  {
    "language_code": "nl",
    "language_name": "Dutch"
  },
  {
    "language_code": "xx-elmer",
    "language_name": "Elmer Fudd"
  },
  {
    "language_code": "en",
    "language_name": "English"
  },
  {
    "language_code": "eo",
    "language_name": "Esperanto"
  },
  {
    "language_code": "et",
    "language_name": "Estonian"
  },
  {
    "language_code": "ee",
    "language_name": "Ewe"
  },
  {
    "language_code": "fo",
    "language_name": "Faroese"
  },
  {
    "language_code": "tl",
    "language_name": "Filipino"
  },
  {
    "language_code": "fi",
    "language_name": "Finnish"
  },
  {
    "language_code": "fr",
    "language_name": "French"
  },
  {
    "language_code": "fy",
    "language_name": "Frisian"
  },
  {
    "language_code": "gaa",
    "language_name": "Ga"
  },
  {
    "language_code": "gl",
    "language_name": "Galician"
  },
  {
    "language_code": "ka",
    "language_name": "Georgian"
  },
  {
    "language_code": "de",
    "language_name": "German"
  },
  {
    "language_code": "el",
    "language_name": "Greek"
  },
  {
    "language_code": "kl",
    "language_name": "Greenlandic"
  },
  {
    "language_code": "gn",
    "language_name": "Guarani"
  },
  {
    "language_code": "gu",
    "language_name": "Gujarati"
  },
  {
    "language_code": "xx-hacker",
    "language_name": "Hacker"
  },
  {
    "language_code": "ht",
    "language_name": "Haitian Creole"
  },
  {
    "language_code": "ha",
    "language_name": "Hausa"
  },
  {
    "language_code": "haw",
    "language_name": "Hawaiian"
  },
  {
    "language_code": "iw",
    "language_name": "Hebrew"
  },
  {
    "language_code": "hi",
    "language_name": "Hindi"
  },
  {
    "language_code": "hu",
    "language_name": "Hungarian"
  },
  {
    "language_code": "is",
    "language_name": "Icelandic"
  },
  {
    "language_code": "ig",
    "language_name": "Igbo"
  },
  {
    "language_code": "id",
    "language_name": "Indonesian"
  },
  {
    "language_code": "ia",
    "language_name": "Interlingua"
  },
  {
    "language_code": "ga",
    "language_name": "Irish"
  },
  {
    "language_code": "it",
    "language_name": "Italian"
  },
  {
    "language_code": "ja",
    "language_name": "Japanese"
  },
  {
    "language_code": "jw",
    "language_name": "Javanese"
  },
  {
    "language_code": "kn",
    "language_name": "Kannada"
  },
  {
    "language_code": "kk",
    "language_name": "Kazakh"
  },
  {
    "language_code": "rw",
    "language_name": "Kinyarwanda"
  },
  {
    "language_code": "rn",
    "language_name": "Kirundi"
  },
  {
    "language_code": "xx-klingon",
    "language_name": "Klingon"
  },
  {
    "language_code": "kg",
    "language_name": "Kongo"
  },
  {
    "language_code": "ko",
    "language_name": "Korean"
  },
  {
    "language_code": "kri",
    "language_name": "Krio (Sierra Leone)"
  },
  {
    "language_code": "ku",
    "language_name": "Kurdish"
  },
  {
    "language_code": "ckb",
    "language_name": "Kurdish (Soranî)"
  },
  {
    "language_code": "ky",
    "language_name": "Kyrgyz"
  },
  {
    "language_code": "lo",
    "language_name": "Laothian"
  },
  {
    "language_code": "la",
    "language_name": "Latin"
  },
  {
    "language_code": "lv",
    "language_name": "Latvian"
  },
  {
    "language_code": "ln",
    "language_name": "Lingala"
  },
  {
    "language_code": "lt",
    "language_name": "Lithuanian"
  },
  {
    "language_code": "loz",
    "language_name": "Lozi"
  },
  {
    "language_code": "lg",
    "language_name": "Luganda"
  },
  {
    "language_code": "ach",
    "language_name": "Luo"
  },
  {
    "language_code": "mk",
    "language_name": "Macedonian"
  },
  {
    "language_code": "mg",
    "language_name": "Malagasy"
  },
  {
    "language_code": "my",
    "language_name": "Malay"
  },
  {
    "language_code": "ml",
    "language_name": "Malayalam"
  },
  {
    "language_code": "mt",
    "language_name": "Maltese"
  },
  {
    "language_code": "mv",
    "language_name": "Maldives"
  },
  {
    "language_code": "mi",
    "language_name": "Maori"
  },
  {
    "language_code": "mr",
    "language_name": "Marathi"
  },
  {
    "language_code": "mfe",
    "language_name": "Mauritian Creole"
  },
  {
    "language_code": "mo",
    "language_name": "Moldavian"
  },
  {
    "language_code": "mn",
    "language_name": "Mongolian"
  },
  {
    "language_code": "sr-me",
    "language_name": "Montenegrin"
  },
  {
    "language_code": "ne",
    "language_name": "Nepali"
  },
  {
    "language_code": "pcm",
    "language_name": "Nigerian Pidgin"
  },
  {
    "language_code": "nso",
    "language_name": "Northern Sotho"
  },
  {
    "language_code": "no",
    "language_name": "Norwegian"
  },
  {
     [...]

2022-09-14 13:17 UTC, humanolaranja commented
I need help to fix this two codecov failing tasks

2022-09-14 16:03 UTC, humanolaranja commented
I need help to fix this last codecov failing task

2022-09-15 12:32 UTC, humanolaranja commented
@larryaasen

2022-09-18 14:58 UTC, larryaasen commented on lib/src/play_store_search_api.dart
> +    if (country != null && country.isNotEmpty) {
```suggestion
    if (language != null && language.isNotEmpty) {
```

2022-09-18 15:45 UTC, humanolaranja commented
Fixed your comment @larryaasen 
Just need help with `codecov/patch`

2022-09-30 12:01 UTC, humanolaranja commented
This library still being maintained @larryaasen ? I really need this pr features and I'd like to know if a fork the entire library or wait for the pr being merged

2022-10-05 13:25 UTC, humanolaranja commented
@larryaasen

2022-10-10 22:26 UTC, larryaasen requested changes
Looks good to me. There are two file conflicts that need to be resolved before this PR can be merged.

2022-10-10 22:50 UTC, humanolaranja commented
`codecov/patch` still a problem, but I solved all conflicts

2022-10-11 13:51 UTC, humanolaranja commented
@larryaasen

2022-10-12 12:43 UTC, larryaasen approved these changes
LGTM

2022-10-12 12:43 UTC, merged

2022-10-13 19:32 UTC, humanolaranja commented
So now can we make a new release in pub.dev with this PR?