Pashto language localization
larryaasen/upgrader pull request #447
Opened 2024-09-15 10:57 UTC by isshort

2024-09-15 11:02 UTC, isshort commented
This branch is linked to #310

2024-09-22 15:34 UTC, larryaasen commented
@isshort Thanks for your PR. The 'ps' language name should be listed after 'pl' and before 'ru' to keep them alphabetized in English. Can you make that change?

2024-09-22 15:35 UTC, larryaasen requested changes
@isshort Thanks for your PR. The 'ps' language name should be listed after 'pl' and before 'ru' to keep them alphabetized in English. Can you make that change?

2024-09-23 11:45 UTC, larryaasen commented on lib/src/upgrade_messages.dart
> +
```suggestion

```

2024-09-23 11:48 UTC, merged

2024-09-23 12:07 UTC, larryaasen commented
This change was published in version 11.2.0.
https://pub.dev/packages/upgrader/versions/11.2.0